### ISSUE TITLE
Adding Adjusment variable to to_hijri.

### ISSUE THREAD

**Issue by NuhaKhaled** [ecleel/hijri#6]
The hijri dates depends on countries, so it will be great if you added Adjustment parameter that can help us to tune the output. 

Example: 

hijri_date = Date.today.to_hijri   #equals = Friday 17 Ramadan while it is 16 Ramadan in Egypt.

so needed add would simple be

hijri_date = Date.today.to_hijri(-1)  #equals = Friday 16 Ramadan

**Comment by ecleel** [comment]
the issue has been resolved in [v0.6.0](https://github.com/ecleel/hijri/commit/6afdfad3f4aa8b80eeae2bdfd4a2cc9a253421be)
